"""Correction relations User et ReferralBonus

Revision ID: 48d53722e785
Revises: 4ae2d4c72d12
Create Date: 2025-03-27 16:39:17.480211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d53722e785'
down_revision: Union[str, None] = '4ae2d4c72d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('winnings', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bets', sa.Column('is_demo', sa.Integer(), nullable=False))
    op.add_column('bets', sa.Column('first_group', sa.String(), nullable=False))
    op.add_column('bets', sa.Column('second_group', sa.String(), nullable=False))
    op.alter_column('users', 'total_winnings',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'referral_earnings',
               existing_type=sa.NUMERIC(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_users_username', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.alter_column('users', 'referral_earnings',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_winnings',
               existing_type=sa.NUMERIC(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('bets', 'second_group')
    op.drop_column('bets', 'first_group')
    op.drop_column('bets', 'is_demo')
    op.drop_column('bets', 'winnings')
    # ### end Alembic commands ###
