"""Fix ambiguous foreign key issue

Revision ID: 4ae2d4c72d12
Revises: ee5cbdaa0b15
Create Date: 2025-03-17 06:45:01.806895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ae2d4c72d12'
down_revision: Union[str, None] = 'ee5cbdaa0b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
